### ISSUE TITLE
`:help bufferline` not working

### ISSUE THREAD

**Issue by lsmag** [bling/vim-bufferline#13]
I installed bufferline with Pathogen, and I'm trying to use with vim-airline, but the command quoted above does not work, it simply says "Sorry, there's no help for bufferline".

What seems odd to me is that bufferline is actually working, it shows my buffers on statusline (I tested removing vim-bufferline from bundle/ to see what happens).

My repository is [here](https://github.com/lsmag/vim-config) (it's very young and undocumented). I'm using a compiled Vim 7.4 on Ubuntu 13.04.

What can be happening?

**Comment by JakeSummers** [comment]
I am having a related issue.  

When I run `:help bufferline` I am linked to airlines section on bufferline.  Is this the expected behavior?
