### ISSUE TITLE
DOS style line breaks do not work under *nix

### ISSUE THREAD

**Issue by h4emp3** [bling/vim-bufferline#14]
For a few months now I have to apply the dos2unix tool on the file plugin/bufferline.vim as it contains DOS style line breaks which do not work under unixoid operating systems (e.g. Linux). I hoped for it to be recognized and delayed filing this bug too often. This happened sometime this year, so I assume it was not intentional. Please change it back!

Error thrown after adding this plugin:
$ vim
Error detected while processing /home/<user>/.vim/bundle/vim-bufferline/plugin/bufferline.vim:
line    1:
E15: Invalid expression: !exists('g:bufferline_active_buffer_left')^M
line  127:
E171: Missing :endif
Press ENTER or type command to continue

Possible way to fix this issue:
$ dos2unix /home/<user>/.vim/bundle/vim-bufferline/plugin/bufferline.vim
dos2unix: converting file /home/<user>/.vim/bundle/vim-bufferline/plugin/bufferline.vim to Unix format ...

OMG, I am very very sorry, this is not true at all! I'm installing plugins via vundle and I just used the wrong bundle string (vim-bufferline instead of bling/vim-bufferline) which caused vundle to install the vim-scripts version of this plugin! Please forgive me...

**Comment by cmeissner** [comment]
Actually it's this error is back if I install plugin with Vundle on my mac.
