### ISSUE TITLE
Display buffer indices only' on bufferline? (not status or command line)

### ISSUE THREAD

**Issue by vexe** [bling/vim-bufferline#20]
First thanks for the plugin. So I was a bit curious why you elected to show buffer indices in the statusline/commandbar and not the tabline - it's just confusing. why would I display buffers at one line and look at their indices at another? here's a screen shot

![result](https://cloud.githubusercontent.com/assets/1978827/4029807/8a4bb468-2c55-11e4-8e8a-5567b6ee8360.png)

I was wondering if there's any way to hide the indices/buffernumbers from the commandbar and statusline and just show them at the top tabline? - I think that's more intuitive (that's what I expected to see at first) - or at least just hide the indices/buffers from the statusline - then I could hide the tabline and just use the commandbar to see the tab with their indices. and just let the statusline display the current file I'm editing. I just want to look at one place.
My settings:

```
"bufferline"
    let g:bufferline_modified = '*'

"Airline"
    " Enable the list of buffers
    let g:airline#extensions#tabline#enabled=1

    " Show just the filename
    let g:airline#extensions#tabline#fnamemod=':t'

    " enable/disable displaying buffers with a single tab
    let g:airline#extensions#tabline#show_buffers = 1
```

Thanks.

**Comment by geoffreyvanwyk** [comment]
Exit and restart GVim for this to kick-in.
