### ISSUE TITLE
Statusline integration doesn't work for me

### ISSUE THREAD

**Issue by wimstefan** [bling/vim-bufferline#3]
I try to implement the status line integration as shown in the help with:

let g:bufferline_echo=0
let &statusline='%{bufferline#refresh_status()}'  
let &statusline.=bufferline#get_status_string()

but I always get this error:

E117: Unknown function: bufferline#get_status_string
E15: Invalid expression: bufferline#get_status_string()

I already disabled all other statusline config that I was using ...

PS: This is used together with vim-airline (not sure if that's of any importance).

**Comment by kenardes** [comment]
hello noobs here, want to ask, how to make the list of buffer just shown on command bar? i don't want it to be shown on airline statusline.
The behaviour that i want is, airline statusline just show the full path of current buffer / open file (default behaviour), while buffer list show on command bar. 
or just let airline show buffer list like current behaviour (airline integration), but for command line instead show list of buffer too it show current buffer / open file full path.
