### ISSUE TITLE
powerline fonts

### ISSUE THREAD

**Issue by ScriptorNY** [bling/vim-bufferline#30]
Hello,

I would like to know if it is possible to use powerline fonts when using bufferline ?
I know there is an option for the delimiters, but to be more specific, is there something more automatic that can be done ?

Thank you in advance for any response

**Comment by bling** [comment]
if you check the airline docs https://github.com/bling/vim-airline/blob/master/doc/airline.txt#L174 you can just copy paste the characters from there and modify `g:bufferline_active_buffer_left` and `g:bufferline_active_buffer_right` respectively.

**Comment by ScriptorNY** [comment]
Thank you very much :)
