### ISSUE TITLE
How to show line/column numbers with statusline integration

### ISSUE THREAD

**Issue by Henderake** [bling/vim-bufferline#46]
When enabling statusline integration, how do I display current line number and columns just like the default vim statusline?
Thanks!

**Comment by tawtao** [comment]
How do you resolve the issue? I have the same issue here.

**Comment by Henderake** [comment]
I can't remember the details on how I solved it. Here's the settings in my `.vimrc`:

```vim
let g:bufferline_echo = 0
let g:bufferline_rotate = 2
autocmd VimEnter *
    \ let &statusline='%{bufferline#refresh_status()}'
        \ . bufferline#get_status_string()
        \ . ' %{&ff}'
        \ . ' %<%F'
        \ . '%m'
        \ . '%r'
        \ . '%=%5l'
        \ . '/%L'
        \ . '%4v'
        \ . ' %#warningmsg#'
        \ . '%{SyntasticStatuslineFlag()}'
        \ . '%*'
```

In the above setting I incorporate the status from `Syntastic` plugin. Delete the corresponding line if you don't need it.

**Comment by tawtao** [comment]
Thanks, appreciate you sharing your solution.
